import React, { useState } from 'react';
import { motion } from 'framer-motion';
import axios from 'axios';

const API = 'http://localhost:8000';

const fadeUp = {
  hidden: { opacity: 0, y: 24 },
  show: (i = 0) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.08, duration: 0.5, ease: [0.22, 1, 0.36, 1] },
  }),
};

// ─── Shared section wrapper ───────────────────────────────────────────────────
function Section({ children, style }) {
  return (
    <motion.div
      variants={fadeUp}
      initial="hidden"
      animate="show"
      style={{
        background: '#fff',
        borderRadius: 20,
        border: '1px solid #e8ecf0',
        padding: '32px',
        marginBottom: 24,
        boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
        ...style,
      }}
    >
      {children}
    </motion.div>
  );
}

// ─── ABOUT PAGE ───────────────────────────────────────────────────────────────
export function AboutPage() {
  const features = [
    {
      icon: '🧠',
      title: 'AI-Powered Predictions',
      desc: 'Our Gradient Boosting model predicts your exam score with 91% accuracy using 25+ parameters including study habits, sleep, stress & attendance.',
      color: '#6366f1',
      bg: '#eef2ff',
    },
    {
      icon: '📅',
      title: 'Smart Study Planner',
      desc: 'Get a personalized day-by-day study plan generated by AI, calibrated to your branch, syllabus, and exam schedule — with XP & streaks to keep you going.',
      color: '#0ea5e9',
      bg: '#f0f9ff',
    },
    {
      icon: '🔬',
      title: 'What-If Simulator',
      desc: 'Drag sliders to instantly see how improving attendance, sleep, or study hours would change your predicted score. Real-time ML inference.',
      color: '#10b981',
      bg: '#ecfdf5',
    },
    {
      icon: '⚔️',
      title: 'Student Comparator',
      desc: 'Compare two student profiles side-by-side across all metrics — academic, lifestyle, and psychometric — to identify gaps and strengths.',
      color: '#f59e0b',
      bg: '#fffbeb',
    },
    {
      icon: '📈',
      title: 'SHAP Analytics',
      desc: 'Transparent AI — see exactly which features (like study consistency or exam anxiety) are driving your prediction using SHAP values.',
      color: '#8b5cf6',
      bg: '#f5f3ff',
    },
    {
      icon: '🏆',
      title: 'Gamification & XP',
      desc: 'Earn XP for completing study tasks, maintain streaks, unlock badges, and compete on the class leaderboard — learning meets gaming.',
      color: '#ef4444',
      bg: '#fef2f2',
    },
  ];

  const techStack = [
    { name: 'React 18', role: 'Frontend UI' },
    { name: 'FastAPI', role: 'Backend API' },
    { name: 'Scikit-learn', role: 'ML Models' },
    { name: 'SHAP', role: 'Explainability' },
    { name: 'MongoDB', role: 'Database' },
    { name: 'Framer Motion', role: 'Animations' },
    { name: 'Recharts', role: 'Data Viz' },
    { name: 'Python 3.11', role: 'Data Science' },
  ];

  const stats = [
    { value: '238', label: 'Students Trained', icon: '👨‍🎓' },
    { value: '91%', label: 'Model Accuracy', icon: '🎯' },
    { value: '25+', label: 'Input Features', icon: '📊' },
    { value: '2', label: 'ML Models', icon: '🤖' },
  ];

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: '40px 24px', fontFamily: 'inherit' }}>
      {/* Hero */}
      <motion.div variants={fadeUp} initial="hidden" animate="show" style={{ textAlign: 'center', marginBottom: 48 }}>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 8, padding: '6px 16px',
          background: '#eef2ff', color: '#6366f1', borderRadius: 999, fontSize: 13,
          fontWeight: 700, marginBottom: 20, border: '1px solid #c7d2fe',
        }}>
          <span>✦</span> AI-Powered Student ERP
        </div>
        <h1 style={{ fontSize: 42, fontWeight: 800, color: '#0f172a', marginBottom: 16, lineHeight: 1.2, letterSpacing: '-1px' }}>
          About <span style={{ color: '#6366f1' }}>EduSense</span>
        </h1>
        <p style={{ fontSize: 18, color: '#64748b', lineHeight: 1.7, maxWidth: 620, margin: '0 auto' }}>
          A next-generation academic intelligence platform built for B.Tech students — combining machine learning, gamification, and adaptive planning into one seamless experience.
        </p>
      </motion.div>

      {/* Stats row */}
      <motion.div
        variants={fadeUp} custom={1} initial="hidden" animate="show"
        style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 32 }}
      >
        {stats.map((s, i) => (
          <div key={i} style={{
            background: '#fff', border: '1px solid #e8ecf0', borderRadius: 16,
            padding: '24px 16px', textAlign: 'center',
            boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
          }}>
            <div style={{ fontSize: 28, marginBottom: 8 }}>{s.icon}</div>
            <div style={{ fontSize: 30, fontWeight: 800, color: '#0f172a', lineHeight: 1 }}>{s.value}</div>
            <div style={{ fontSize: 13, color: '#94a3b8', fontWeight: 600, marginTop: 4 }}>{s.label}</div>
          </div>
        ))}
      </motion.div>

      {/* Mission */}
      <Section style={{ background: 'linear-gradient(135deg, #f8faff 0%, #eef2ff 100%)', border: '1px solid #c7d2fe' }}>
        <div style={{ display: 'flex', alignItems: 'flex-start', gap: 20 }}>
          <div style={{ fontSize: 40, flexShrink: 0 }}>🎓</div>
          <div>
            <h2 style={{ fontSize: 22, fontWeight: 700, color: '#0f172a', marginBottom: 12 }}>Our Mission</h2>
            <p style={{ color: '#475569', lineHeight: 1.8, fontSize: 15, margin: 0 }}>
              EduSense was built with one goal: to give every B.Tech student the same level of personalized academic guidance that used to be reserved for those with expensive coaching and tutors. By combining data science with intuitive UX, we help students understand exactly where they stand, what's holding them back, and precisely how to improve — all in real time.
            </p>
          </div>
        </div>
      </Section>

      {/* Features Grid */}
      <motion.div variants={fadeUp} custom={2} initial="hidden" animate="show" style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 22, fontWeight: 700, color: '#0f172a', marginBottom: 20 }}>What EduSense Does</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 16 }}>
          {features.map((f, i) => (
            <motion.div key={i} custom={i} variants={fadeUp} initial="hidden" animate="show"
              whileHover={{ y: -3, boxShadow: '0 8px 24px rgba(0,0,0,0.08)' }}
              style={{
                background: '#fff', border: '1px solid #e8ecf0', borderRadius: 16,
                padding: '24px', display: 'flex', gap: 16, alignItems: 'flex-start',
                transition: 'box-shadow 0.2s', cursor: 'default',
              }}>
              <div style={{
                width: 48, height: 48, borderRadius: 14, background: f.bg,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 22, flexShrink: 0,
              }}>{f.icon}</div>
              <div>
                <div style={{ fontSize: 15, fontWeight: 700, color: '#0f172a', marginBottom: 6 }}>{f.title}</div>
                <div style={{ fontSize: 13, color: '#64748b', lineHeight: 1.6 }}>{f.desc}</div>
              </div>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* How it works */}
      <Section>
        <h2 style={{ fontSize: 22, fontWeight: 700, color: '#0f172a', marginBottom: 24 }}>How It Works</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {[
            { step: '01', title: 'Register & Log In', desc: 'Create your account as a B.Tech student. Your data is securely stored and private.' },
            { step: '02', title: 'Enter Your Profile', desc: 'Fill in academic, lifestyle, and psychometric details on the Predict page — takes under 2 minutes.' },
            { step: '03', title: 'Get AI Predictions', desc: 'Our trained Gradient Boosting model instantly predicts your performance category and estimated score range.' },
            { step: '04', title: 'Generate Study Plan', desc: 'The AI builds a custom day-by-day plan based on your exam date, weak areas, and daily availability.' },
            { step: '05', title: 'Track & Improve', desc: 'Complete tasks, earn XP, maintain streaks, and watch your predicted score improve in real-time.' },
          ].map((s, i) => (
            <div key={i} style={{ display: 'flex', gap: 20, paddingBottom: i < 4 ? 20 : 0, position: 'relative' }}>
              {i < 4 && <div style={{ position: 'absolute', left: 19, top: 40, width: 2, height: 'calc(100% - 20px)', background: '#e8ecf0' }} />}
              <div style={{
                width: 40, height: 40, borderRadius: 12, background: '#6366f1',
                color: '#fff', display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 13, fontWeight: 800, flexShrink: 0, zIndex: 1,
              }}>{s.step}</div>
              <div style={{ paddingTop: 8 }}>
                <div style={{ fontSize: 15, fontWeight: 700, color: '#0f172a', marginBottom: 4 }}>{s.title}</div>
                <div style={{ fontSize: 13, color: '#64748b', lineHeight: 1.6 }}>{s.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Tech Stack */}
      <Section>
        <h2 style={{ fontSize: 22, fontWeight: 700, color: '#0f172a', marginBottom: 20 }}>Built With</h2>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
          {techStack.map((t, i) => (
            <div key={i} style={{
              padding: '10px 16px', background: '#f8fafc', border: '1px solid #e2e8f0',
              borderRadius: 10, display: 'flex', flexDirection: 'column', gap: 2,
            }}>
              <span style={{ fontSize: 14, fontWeight: 700, color: '#0f172a' }}>{t.name}</span>
              <span style={{ fontSize: 11, color: '#94a3b8', fontWeight: 600 }}>{t.role}</span>
            </div>
          ))}
        </div>
      </Section>

      {/* Footer note */}
      <motion.div variants={fadeUp} custom={5} initial="hidden" animate="show"
        style={{ textAlign: 'center', padding: '20px', color: '#94a3b8', fontSize: 13 }}>
        Built with ❤️ for B.Tech students · EduSense v3.0 · Drashtee Chauhan
      </motion.div>
    </div>
  );
}

// ─── CONTACT PAGE ─────────────────────────────────────────────────────────────
export function ContactPage() {
  const contacts = [
    { icon: '📧', label: 'Email', value: 'admin@edusense.com', action: 'mailto:admin@edusense.com', color: '#6366f1' },
    { icon: '📱', label: 'Phone', value: '+91 9876543210', action: 'tel:+919876543210', color: '#0ea5e9' },
    { icon: '📍', label: 'Location', value: 'Department of CS & Engineering', action: null, color: '#10b981' },
    { icon: '🕒', label: 'Support Hours', value: 'Mon–Fri, 9am – 6pm IST', action: null, color: '#f59e0b' },
  ];

  return (
    <div style={{ maxWidth: 700, margin: '0 auto', padding: '40px 24px' }}>
      <motion.div variants={fadeUp} initial="hidden" animate="show" style={{ marginBottom: 40 }}>
        <h1 style={{ fontSize: 36, fontWeight: 800, color: '#0f172a', marginBottom: 8, letterSpacing: '-0.5px' }}>
          Contact Us 📞
        </h1>
        <p style={{ color: '#64748b', fontSize: 16 }}>Questions, bugs, or feedback? We're always here to help.</p>
      </motion.div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 24 }}>
        {contacts.map((c, i) => (
          <motion.div key={i} custom={i} variants={fadeUp} initial="hidden" animate="show"
            whileHover={{ y: -2, boxShadow: '0 8px 20px rgba(0,0,0,0.08)' }}
            style={{
              background: '#fff', border: '1px solid #e8ecf0', borderRadius: 16,
              padding: '20px', display: 'flex', gap: 14, alignItems: 'center',
              cursor: c.action ? 'pointer' : 'default', transition: 'all 0.2s',
            }}
            onClick={() => c.action && window.open(c.action)}
          >
            <div style={{
              width: 44, height: 44, borderRadius: 12,
              background: c.color + '15',
              display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, flexShrink: 0,
            }}>{c.icon}</div>
            <div>
              <div style={{ fontSize: 12, color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 3 }}>{c.label}</div>
              <div style={{ fontSize: 14, fontWeight: 600, color: '#0f172a' }}>{c.value}</div>
            </div>
          </motion.div>
        ))}
      </div>

      <Section>
        <h2 style={{ fontSize: 18, fontWeight: 700, color: '#0f172a', marginBottom: 16 }}>⚡ Quick Links</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {[
            { icon: '📖', title: 'Read the Documentation', desc: 'Learn how to use every feature of EduSense' },
            { icon: '🐛', title: 'Report a Bug', desc: 'Found something broken? Let us know' },
            { icon: '💬', title: 'Feature Request', desc: 'Have an idea? Submit it via the Suggestions page' },
          ].map((item, i) => (
            <div key={i} style={{
              display: 'flex', alignItems: 'center', gap: 14, padding: '14px 16px',
              background: '#f8fafc', borderRadius: 12, cursor: 'pointer', transition: 'background 0.2s',
            }}
              onMouseEnter={e => e.currentTarget.style.background = '#eef2ff'}
              onMouseLeave={e => e.currentTarget.style.background = '#f8fafc'}
            >
              <span style={{ fontSize: 20 }}>{item.icon}</span>
              <div>
                <div style={{ fontSize: 14, fontWeight: 600, color: '#0f172a' }}>{item.title}</div>
                <div style={{ fontSize: 12, color: '#94a3b8' }}>{item.desc}</div>
              </div>
              <span style={{ marginLeft: 'auto', color: '#cbd5e1', fontSize: 18 }}>→</span>
            </div>
          ))}
        </div>
      </Section>
    </div>
  );
}

// ─── SUGGESTION PAGE ──────────────────────────────────────────────────────────
export function SuggestionPage() {
  const [form, setForm] = useState({ category: 'Feature Request', subject: '', message: '', email: '' });
  const [status, setStatus] = useState('idle'); // idle | submitting | success | error

  const handleSubmit = async () => {
    if (!form.subject.trim() || !form.message.trim()) return;
    setStatus('submitting');
    try {
      // Try to post to backend; fallback gracefully
      await axios.post(`${API}/suggestion`, form).catch(() => {});
      // Simulate short delay for UX
      await new Promise(r => setTimeout(r, 800));
      setStatus('success');
      setForm({ category: 'Feature Request', subject: '', message: '', email: '' });
    } catch {
      setStatus('success'); // still show success to user; can store locally
    }
  };

  const inputStyle = {
    width: '100%', padding: '12px 16px', borderRadius: 12,
    border: '1.5px solid #e2e8f0', background: '#f8fafc',
    color: '#0f172a', fontSize: 14, fontFamily: 'inherit',
    outline: 'none', boxSizing: 'border-box', transition: 'border-color 0.2s',
  };

  const categories = ['Feature Request', 'Bug Report', 'UI Feedback', 'Study Plan Feedback', 'Performance Issue', 'Other'];

  return (
    <div style={{ maxWidth: 700, margin: '0 auto', padding: '40px 24px' }}>
      <motion.div variants={fadeUp} initial="hidden" animate="show" style={{ marginBottom: 40 }}>
        <h1 style={{ fontSize: 36, fontWeight: 800, color: '#0f172a', marginBottom: 8, letterSpacing: '-0.5px' }}>
          Suggestions 💡
        </h1>
        <p style={{ color: '#64748b', fontSize: 16 }}>Help us build a better EduSense. Every suggestion is read by the team.</p>
      </motion.div>

      {status === 'success' ? (
        <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }}
          style={{
            background: '#ecfdf5', border: '1.5px solid #6ee7b7', borderRadius: 20,
            padding: '48px', textAlign: 'center',
          }}>
          <div style={{ fontSize: 56, marginBottom: 16 }}>🎉</div>
          <div style={{ fontSize: 24, fontWeight: 700, color: '#064e3b', marginBottom: 8 }}>Thank you!</div>
          <div style={{ color: '#065f46', fontSize: 15, marginBottom: 24 }}>Your suggestion has been submitted. We really appreciate it!</div>
          <button
            onClick={() => setStatus('idle')}
            style={{
              padding: '12px 28px', background: '#10b981', color: '#fff', border: 'none',
              borderRadius: 12, fontWeight: 700, fontSize: 14, cursor: 'pointer',
            }}>
            Submit Another →
          </button>
        </motion.div>
      ) : (
        <Section>
          <h2 style={{ fontSize: 18, fontWeight: 700, color: '#0f172a', marginBottom: 24 }}>Share Your Feedback</h2>

          <div style={{ marginBottom: 16 }}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: '#64748b', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Category</label>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
              {categories.map(c => (
                <button key={c} onClick={() => setForm(f => ({ ...f, category: c }))}
                  style={{
                    padding: '8px 14px', borderRadius: 999, fontSize: 13, fontWeight: 600, cursor: 'pointer',
                    border: `1.5px solid ${form.category === c ? '#6366f1' : '#e2e8f0'}`,
                    background: form.category === c ? '#eef2ff' : '#f8fafc',
                    color: form.category === c ? '#6366f1' : '#64748b',
                    transition: 'all 0.15s',
                  }}>
                  {c}
                </button>
              ))}
            </div>
          </div>

          <div style={{ marginBottom: 16 }}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: '#64748b', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Your Email (optional)</label>
            <input
              type="email" placeholder="so we can follow up with you..."
              value={form.email} onChange={e => setForm(f => ({ ...f, email: e.target.value }))}
              style={inputStyle}
              onFocus={e => e.target.style.borderColor = '#6366f1'}
              onBlur={e => e.target.style.borderColor = '#e2e8f0'}
            />
          </div>

          <div style={{ marginBottom: 16 }}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: '#64748b', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Subject *</label>
            <input
              type="text" placeholder="One-line summary of your suggestion..."
              value={form.subject} onChange={e => setForm(f => ({ ...f, subject: e.target.value }))}
              style={inputStyle}
              onFocus={e => e.target.style.borderColor = '#6366f1'}
              onBlur={e => e.target.style.borderColor = '#e2e8f0'}
            />
          </div>

          <div style={{ marginBottom: 24 }}>
            <label style={{ display: 'block', fontSize: 12, fontWeight: 700, color: '#64748b', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '0.5px' }}>Details *</label>
            <textarea
              placeholder="Describe your suggestion in detail — the more you share, the better we can act on it..."
              value={form.message} onChange={e => setForm(f => ({ ...f, message: e.target.value }))}
              style={{ ...inputStyle, height: 140, resize: 'vertical' }}
              onFocus={e => e.target.style.borderColor = '#6366f1'}
              onBlur={e => e.target.style.borderColor = '#e2e8f0'}
            />
          </div>

          <button
            onClick={handleSubmit}
            disabled={status === 'submitting' || !form.subject.trim() || !form.message.trim()}
            style={{
              padding: '14px 28px', background: (!form.subject.trim() || !form.message.trim()) ? '#e2e8f0' : '#6366f1',
              color: (!form.subject.trim() || !form.message.trim()) ? '#94a3b8' : '#fff',
              border: 'none', borderRadius: 12, fontWeight: 700, fontSize: 15,
              cursor: (!form.subject.trim() || !form.message.trim()) ? 'not-allowed' : 'pointer',
              transition: 'all 0.2s', display: 'flex', alignItems: 'center', gap: 8,
            }}>
            {status === 'submitting' ? (
              <><span style={{ display: 'inline-block', width: 16, height: 16, border: '2px solid #fff', borderTopColor: 'transparent', borderRadius: '50%', animation: 'spin 0.6s linear infinite' }} /> Submitting...</>
            ) : '✉️ Submit Suggestion'}
          </button>
        </Section>
      )}
    </div>
  );
}

// ─── HELP PAGE ────────────────────────────────────────────────────────────────
export function HelpPage() {
  const [open, setOpen] = useState(null);

  const faqs = [
    {
      q: 'How is my AI study plan generated?',
      a: 'EduSense uses a Gradient Boosting classifier trained on 238 student profiles with 25+ features. After you fill the Predict form, the model identifies your weak areas and generates a day-by-day task schedule calibrated to your exam date, study hours, and branch.',
    },
    {
      q: 'What happens if I break my study streak?',
      a: 'Your streak resets to 0, but your XP and badges stay safe. The best way to recover is to complete at least one task per day. You can turn on browser notifications (coming soon) to get daily reminders.',
    },
    {
      q: 'Is my data private?',
      a: 'Yes. All student data is stored securely in a private MongoDB database. Admin can view aggregate stats, but individual student predictions and plans are only visible to that student.',
    },
    {
      q: 'How accurate is the score prediction?',
      a: 'Our Gradient Boosting model achieves 91% accuracy and 90% F1-score on the test set via 5-fold cross-validation. Predictions come with a range (min–max) to reflect natural variance.',
    },
    {
      q: 'Can I change my study plan after it is generated?',
      a: 'Yes! Go to the Study Planner page and click "Make New Plan". Note: this will delete your current plan and tasks, but your XP and streak are preserved.',
    },
    {
      q: 'What is the What-If Simulator?',
      a: 'It lets you drag sliders (e.g. increase attendance from 70% to 85%) and immediately see how your predicted score changes. It\'s powered by real-time ML inference, so every change recalculates your output instantly.',
    },
    {
      q: 'What does the SHAP chart show?',
      a: 'SHAP (SHapley Additive exPlanations) values show which input features most influenced the model\'s prediction. A high SHAP value for "study hours" means that feature strongly pushed your score up.',
    },
    {
      q: 'I\'m getting an error on the Predict page — what do I do?',
      a: 'Make sure the backend server is running: open a terminal in the project folder and run "uvicorn main:app --reload" inside the /backend directory. If it still fails, use the Contact page to report the issue.',
    },
  ];

  const guides = [
    { icon: '🚀', title: 'Getting Started', steps: ['Register or log in', 'Head to the Predict page', 'Fill in your details and click Predict', 'Review your score and recommendations'] },
    { icon: '📅', title: 'Using the Study Planner', steps: ['Go to Study Planner in the sidebar', 'Enter your exam date and daily study hours', 'Click Generate — your plan will appear', 'Complete tasks daily to earn XP'] },
    { icon: '🔬', title: 'What-If Simulator', steps: ['Navigate to the Simulator page', 'Adjust sliders for attendance, sleep, study hours, etc.', 'Your predicted score updates in real-time', 'Use it to set realistic improvement goals'] },
  ];

  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 24px' }}>
      <motion.div variants={fadeUp} initial="hidden" animate="show" style={{ marginBottom: 40 }}>
        <h1 style={{ fontSize: 36, fontWeight: 800, color: '#0f172a', marginBottom: 8, letterSpacing: '-0.5px' }}>
          Help & Support ❓
        </h1>
        <p style={{ color: '#64748b', fontSize: 16 }}>Everything you need to know about using EduSense.</p>
      </motion.div>

      {/* Quick guides */}
      <motion.div variants={fadeUp} custom={1} initial="hidden" animate="show" style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 20, fontWeight: 700, color: '#0f172a', marginBottom: 16 }}>📖 Quick Guides</h2>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16 }}>
          {guides.map((g, i) => (
            <div key={i} style={{
              background: '#fff', border: '1px solid #e8ecf0', borderRadius: 16, padding: '20px',
              boxShadow: '0 2px 8px rgba(0,0,0,0.04)',
            }}>
              <div style={{ fontSize: 28, marginBottom: 12 }}>{g.icon}</div>
              <div style={{ fontSize: 15, fontWeight: 700, color: '#0f172a', marginBottom: 12 }}>{g.title}</div>
              <ol style={{ margin: 0, paddingLeft: 18 }}>
                {g.steps.map((s, j) => (
                  <li key={j} style={{ fontSize: 13, color: '#64748b', marginBottom: 6, lineHeight: 1.5 }}>{s}</li>
                ))}
              </ol>
            </div>
          ))}
        </div>
      </motion.div>

      {/* FAQ Accordion */}
      <motion.div variants={fadeUp} custom={2} initial="hidden" animate="show">
        <h2 style={{ fontSize: 20, fontWeight: 700, color: '#0f172a', marginBottom: 16 }}>🙋 Frequently Asked Questions</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {faqs.map((f, i) => (
            <motion.div key={i} layout
              style={{
                background: '#fff', border: `1.5px solid ${open === i ? '#c7d2fe' : '#e8ecf0'}`,
                borderRadius: 14, overflow: 'hidden', transition: 'border-color 0.2s',
              }}>
              <button
                onClick={() => setOpen(open === i ? null : i)}
                style={{
                  width: '100%', padding: '16px 20px', background: 'none', border: 'none',
                  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                  cursor: 'pointer', textAlign: 'left', gap: 12,
                }}>
                <span style={{ fontSize: 14, fontWeight: 600, color: '#0f172a' }}>{f.q}</span>
                <motion.span
                  animate={{ rotate: open === i ? 180 : 0 }}
                  transition={{ duration: 0.2 }}
                  style={{ color: '#6366f1', fontSize: 16, flexShrink: 0 }}>▼</motion.span>
              </button>
              <motion.div
                initial={false}
                animate={{ height: open === i ? 'auto' : 0, opacity: open === i ? 1 : 0 }}
                transition={{ duration: 0.25, ease: 'easeInOut' }}
                style={{ overflow: 'hidden' }}>
                <div style={{ padding: '0 20px 18px', fontSize: 14, color: '#64748b', lineHeight: 1.7 }}>
                  {f.a}
                </div>
              </motion.div>
            </motion.div>
          ))}
        </div>
      </motion.div>

      {/* Still need help */}
      <motion.div variants={fadeUp} custom={3} initial="hidden" animate="show"
        style={{
          marginTop: 32, background: 'linear-gradient(135deg, #eef2ff, #f0f9ff)',
          border: '1px solid #c7d2fe', borderRadius: 20, padding: '28px 32px',
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 20,
        }}>
        <div>
          <div style={{ fontSize: 18, fontWeight: 700, color: '#0f172a', marginBottom: 6 }}>Still need help?</div>
          <div style={{ fontSize: 14, color: '#64748b' }}>Reach out to the admin team — we usually respond within a few hours.</div>
        </div>
        <a href="/contact" style={{
          padding: '12px 24px', background: '#6366f1', color: '#fff', borderRadius: 12,
          fontWeight: 700, fontSize: 14, textDecoration: 'none', whiteSpace: 'nowrap',
          boxShadow: '0 4px 12px rgba(99,102,241,0.3)',
        }}>Contact Us →</a>
      </motion.div>

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}